apiVersion: v1
kind: Pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      valuefrom:
        configMapKeyRef:
          name: nginx-config
          key: course
    - name: duration
      onfigMapKeyRef:
          name: nginx-config
          key: duration